spring.application.name=JPA with Spring Boot and H2
server.port=8081

# JPA defaults (safe for dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger (Springdoc)
springdoc.api-doc.enabled=true
springdoc.swagger-ui.enabled=true
